-- SQL Schema for Haubach Haus Menu CMS
-- Instructions: Paste this entirely into the Supabase SQL Editor and hit 'Run'

-- 1. Create the Menu Items table
CREATE TABLE public.menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    "desc" TEXT,
    price DECIMAL(10,2) NOT NULL,
    status TEXT,
    "holdReason" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Insert the Default Seeded Menu Data
INSERT INTO public.menu (category, name, "desc", price) VALUES
    ('Starters', 'Hausgemachte Flädlesuppe', 'Clear beef broth, savory crepe strips', 7.50),
    ('Starters', 'Rindercarpaccio', 'Truffle oil, parmesan shavings, arugula', 14.50),
    ('Starters', 'Obazda mit Brezel', 'Bavarian cheese spread, fresh pretzel', 9.50),
    ('Main Courses', 'Original Wiener Kalbsschnitzel', 'Veal schnitzel, warm potato salad', 25.90),
    ('Main Courses', 'Zürcher Geschnetzeltes', 'Sliced veal in mushroom cream sauce, rösti', 22.50),
    ('Main Courses', 'Premium Rumpsteak (250g)', 'Herb butter, roasted vegetables', 28.50),
    ('Burgers', 'Haubach Classic Burger', 'Black Angus beef, aged cheddar, signature sauce', 16.90),
    ('Burgers', 'Luxus Trüffel Burger', 'Beef patty, truffle mayo, caramelized onions', 19.50),
    ('Kids Menu', 'Kleines Schnitzel "Zauberlehrling"', 'Small pork schnitzel with french fries', 9.50),
    ('Kids Menu', 'Spätzle der Elfen', 'Swabian noodles with rich gravy', 6.50);

-- 3. Setup Row Level Security (RLS) policies
-- Note: For Phase 1 REST connectivity without intense auth logic, we allow Anonymous Reads but require the authenticated API Key to update.
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
ON public.menu FOR SELECT
USING (true);

CREATE POLICY "Allow admin full access"
ON public.menu FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
